apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuberos.secretName" . }}
  labels:
    app: {{ include "kuberos.name" . }}
    chart: {{ include "kuberos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ .Values.oidc.clientSecret | b64enc }}
