# Default values for kuberos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ministryofjustice/cloud-platform-kuberos
  tag: 1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  host: login.apps.<cp-XXXX>.cloud-platform.service.justice.gov.uk
  tls:
    - secretName: kuberos-tls
      host:
        - login.apps.<cp-XXXX>.cloud-platform.service.justice.gov.uk

resources:
  limits:
    cpu: 1m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

# These values will be supplied by the OIDC provider.
oidc:
  issuerUrl: ""
  clientId: ""
  clientSecret: ""

# Cluster specific values, replace `address` with the external URL to the
# kubernetes API. If you leave `ca` empty, kuberos will use the current
# cluster's CA certificate. Alternativly, you can specify one by passing the
# base64-encoded apiserver CA certificate.
cluster:
  name: "<cp-XXXX>.cloud-platform.service.justice.gov.uk"
  address: "https://XXXXXXXX.XXX.eu-west-2.eks.amazonaws.com"
  ca: ""