name: Build the image when a PR is raised/changed

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  main:
    name: Build the image when a PR is raised/changed
    runs-on: ubuntu-latest
    steps:
    -
        name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            ministryofjustice/cloud-platform-kuberos
    -
        name: Build kuberos image
        run: |
          docker build .